name: CI

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

env:
  RUSTFLAGS: --deny warnings

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Clippy
      run: cargo clippy --all --all-targets
    - name: Format
      run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - name: Check
      run: cargo check
    - name: Test
      shell: bash
      run: cargo test --all
